version: '3.7'
services:
  test: &base
    image: node:alpine
    working_dir: /usr/local/src
    command: npm test
    env_file:
      - secrets/test.env
    environment:
      - JSON_FILE_PATH=sample-list.json
      - MODULE=fake
      - SEED=1
    volumes:
      - .:/usr/local/src
      - node_modules:/usr/local/src/node_modules
    depends_on:
      - echo
  prd:
    <<: *base
    env_file:
      - secrets/prod.env
    environment:
      - JSON_FILE_PATH=secrets/list.json
      - MODULE=twillio
      - SEED=4
  echo:
    image: mendhak/http-https-echo
    ports:
        - "8080:80"
        - "8443:443"

volumes:
  node_modules:
